# Generated by Django 5.0.6 on 2024-10-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
